name: Auto Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0'
    
    - name: Build
      run: |
        xcodebuild -scheme LPhoto -configuration Debug build
      
    - name: Run Tests
      run: |
        xcodebuild test -scheme LPhoto -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' 